version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 9000:9000
      restart: always
      depends_on:
        - backend-user
        - backend-post
        - frontend
  backend-user:
    image: social-media-api-users
    environment:
      SESSION_SECRET: $SESSION_SECRET
      DATABASECONNECTION: $DATABASECONNECTION 
  backend-post:
    image: social-media-api-posts
    environment:
      SESSION_SECRET: $SESSION_SECRET
      DATABASECONNECTION: $DATABASECONNECTION 
  frontend:
    image: social-media-client:local

